import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
const nunito = Nunito({
  weight: ['300','400','700'],
  style: ['normal','italic'],
  subsets: ['vietnamese'],
  variable:'--font-nunito'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  )
}
